# Generated by Django 4.2.6 on 2023-11-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medprob', '0002_alter_bp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bp',
            options={'ordering': ['-date_num', '-time_num']},
        ),
    ]
