# Generated by Django 4.2.6 on 2023-11-10 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('freq', models.CharField(max_length=255)),
                ('start_date_num', models.DateField()),
                ('start_date_str', models.DateField()),
                ('end_date_num', models.DateField()),
                ('end_date_str', models.DateField()),
                ('assoc_medprob', models.JSONField(default=dict)),
                ('note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
