# Generated by Django 4.2.6 on 2023-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='end_date_num',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='med',
            name='end_date_str',
            field=models.DateField(default=None),
        ),
    ]
