# Generated by Django 4.2.6 on 2023-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_alter_med_end_date_num_alter_med_end_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='note',
            field=models.TextField(default=None),
        ),
    ]
