# Generated by Django 4.2.6 on 2023-11-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0003_alter_med_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='end_date_num',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='med',
            name='end_date_str',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='med',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
