# Generated by Django 4.2.6 on 2023-11-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0004_alter_med_end_date_num_alter_med_end_date_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='assoc_medprob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
