# Generated by Django 4.2.6 on 2023-11-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0005_alter_med_assoc_medprob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='med',
            options={'ordering': ['-end_date_num', '-start_date_num']},
        ),
        migrations.RemoveField(
            model_name='med',
            name='route',
        ),
    ]
